"""Task 5.1: Production Telemetry and Tracing for AI Agents.

Provides:
1. `StepTelemetry`: Pydantic schema recording per-step tokens, cost, and latency.
2. `StepTelemetryTracer`: LangChain `BaseCallbackHandler` capturing real-time metrics
   for LLM invocations and tool executions.
3. Pricing engine computing exact USD cost across model providers.
4. LangSmith configuration helper for cloud tracing integration.
5. Structured JSON logging and formatted ASCII trace summary tables.
"""

from __future__ import annotations

import json
import logging
import os
import time
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.messages import BaseMessage
from langchain_core.outputs import LLMResult
from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger("phase_4_agents.telemetry")
if not logger.handlers:
    handler = logging.StreamHandler()
    handler.setFormatter(
        logging.Formatter("[%(asctime)s] [%(levelname)s] [TELEMETRY] %(message)s")
    )
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

# -----------------------------------------------------------------------------
# 1. Model Pricing Catalog ($ / 1 Million Tokens)
# -----------------------------------------------------------------------------

MODEL_RATES: dict[str, tuple[float, float]] = {
    # model_substring: (input_price_per_1M, output_price_per_1M)
    "gemini-2.5-flash": (0.15, 0.60),
    "gemini-2.0-flash": (0.15, 0.60),
    "gemini-1.5-flash": (0.15, 0.60),
    "gemini-1.5-pro": (1.25, 5.00),
    "gpt-4o-mini": (0.15, 0.60),
    "gpt-4o": (2.50, 10.00),
    "claude-3-5-haiku": (0.80, 4.00),
    "claude-3-5-sonnet": (3.00, 15.00),
    "mock": (0.15, 0.60),
    "default": (0.15, 0.60),
}


def calculate_token_cost(
    model_name: str,
    input_tokens: int,
    output_tokens: int,
) -> float:
    """Calculate the estimated USD cost for a given token usage and model.

    Args:
        model_name: Model identifier string.
        input_tokens: Number of prompt/input tokens.
        output_tokens: Number of completion/output tokens.

    Returns:
        Total estimated cost in USD rounded to 8 decimal places.
    """
    m_lower = (model_name or "default").lower()
    in_rate, out_rate = MODEL_RATES["default"]

    for pattern, rates in MODEL_RATES.items():
        if pattern in m_lower:
            in_rate, out_rate = rates
            break

    input_cost = (input_tokens / 1_000_000.0) * in_rate
    output_cost = (output_tokens / 1_000_000.0) * out_rate
    return round(input_cost + output_cost, 8)


# -----------------------------------------------------------------------------
# 2. Step Telemetry Schema
# -----------------------------------------------------------------------------


class StepTelemetry(BaseModel):
    """Structured metrics recorded for a discrete step in an agent run."""

    model_config = ConfigDict(extra="forbid")

    step_number: int = Field(
        ..., description="Monotonically increasing step number in the execution trace."
    )
    step_type: str = Field(
        ..., description="Type of step ('llm_call', 'tool_execution', 'node_update')."
    )
    node_or_tool: str = Field(
        ..., description="Name of the executing graph node or tool."
    )
    start_time: str = Field(
        ..., description="ISO 8601 UTC timestamp when step execution began."
    )
    end_time: str = Field(
        ..., description="ISO 8601 UTC timestamp when step execution concluded."
    )
    latency_ms: float = Field(
        ..., description="Elapsed execution wall-clock time in milliseconds."
    )
    input_tokens: int = Field(
        default=0, description="Input/prompt token count consumed by this step."
    )
    output_tokens: int = Field(
        default=0, description="Output/completion token count generated by this step."
    )
    total_tokens: int = Field(
        default=0, description="Total tokens (input + output) for this step."
    )
    cost_usd: float = Field(
        default=0.0, description="Estimated USD cost calculated from model rates."
    )
    status: str = Field(
        default="success",
        description="Execution status ('success', 'error', 'paused').",
    )
    input_preview: str = Field(
        default="", description="Sanitized preview of input arguments or prompt."
    )
    output_preview: str = Field(
        default="", description="Sanitized preview of output response or tool result."
    )
    error_message: str | None = Field(
        default=None, description="Detailed error description if execution failed."
    )

    def to_log_dict(self) -> dict[str, Any]:
        """Convert telemetry to a JSON-serializable dictionary for logging."""
        return self.model_dump()


# -----------------------------------------------------------------------------
# 3. LangChain Callback Handler for Real-Time Step Tracing
# -----------------------------------------------------------------------------


class StepTelemetryTracer(BaseCallbackHandler):
    """Production callback handler capturing per-step tokens, cost, and latency.

    Hooks into LangChain and LangGraph runtimes, tracking:
    - Exact start/end timestamps and millisecond latency for each step.
    - Exact or tokenizer-estimated token counts.
    - USD cost calculated against active provider rates.
    - Structured JSON logging per step.
    """

    def __init__(
        self,
        default_model: str = "gemini-2.5-flash",
        log_to_console: bool = True,
    ) -> None:
        super().__init__()
        self.default_model = default_model
        self.log_to_console = log_to_console
        self.steps: list[StepTelemetry] = []
        self._step_counter = 0

        # In-flight active runs tracked by UUID string
        self._active_runs: dict[str, dict[str, Any]] = {}

    def reset(self) -> None:
        """Clear recorded steps and active runs for reuse."""
        self.steps.clear()
        self._step_counter = 0
        self._active_runs.clear()

    # --- LLM / Chat Model Events ---

    def on_chat_model_start(
        self,
        serialized: dict[str, Any] | None,
        messages: list[list[BaseMessage]],
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when a chat model begins execution."""
        run_key = str(run_id)
        start_perf = time.perf_counter()
        start_iso = datetime.now(timezone.utc).isoformat()

        prompt_chars = 0
        preview = ""
        if messages and messages[0]:
            prompt_chars = sum(len(str(m.content)) for m in messages[0])
            preview = str(messages[0][-1].content)[:120].replace("\n", " ")

        model_name = (
            (metadata or {}).get("ls_model_name")
            or (serialized or {}).get("name")
            or self.default_model
        )

        self._active_runs[run_key] = {
            "type": "llm_call",
            "name": "call_model",
            "model_name": model_name,
            "start_perf": start_perf,
            "start_iso": start_iso,
            "prompt_chars": prompt_chars,
            "preview": preview,
        }

    def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when LLM execution successfully concludes."""
        run_key = str(run_id)
        active = self._active_runs.pop(run_key, None)
        end_perf = time.perf_counter()
        end_iso = datetime.now(timezone.utc).isoformat()

        start_perf = active["start_perf"] if active else end_perf
        start_iso = active["start_iso"] if active else end_iso
        latency_ms = round((end_perf - start_perf) * 1000.0, 2)
        model_name = (
            active.get("model_name", self.default_model)
            if active
            else self.default_model
        )
        input_preview = active.get("preview", "") if active else ""

        # Extract tokens from LLMResult metadata
        in_tok = 0
        out_tok = 0
        output_preview = ""

        if response.llm_output and "token_usage" in response.llm_output:
            usage = response.llm_output["token_usage"]
            in_tok = int(usage.get("prompt_tokens", 0))
            out_tok = int(usage.get("completion_tokens", 0))

        if response.generations and response.generations[0]:
            first_gen = response.generations[0][0]
            output_preview = first_gen.text[:120].replace("\n", " ")
            msg = getattr(first_gen, "message", None)
            if msg:
                usage_meta = getattr(msg, "usage_metadata", None)
                if usage_meta:
                    in_tok = in_tok or int(usage_meta.get("input_tokens", 0))
                    out_tok = out_tok or int(usage_meta.get("output_tokens", 0))

        # Fallback estimation if model provider did not supply token counts
        if in_tok == 0 and out_tok == 0 and active:
            in_tok = max(1, active["prompt_chars"] // 4)
            out_tok = max(1, len(output_preview) // 4)

        total_tok = in_tok + out_tok
        cost_usd = calculate_token_cost(model_name, in_tok, out_tok)

        self._step_counter += 1
        step = StepTelemetry(
            step_number=self._step_counter,
            step_type="llm_call",
            node_or_tool=active.get("name", "call_model") if active else "call_model",
            start_time=start_iso,
            end_time=end_iso,
            latency_ms=latency_ms,
            input_tokens=in_tok,
            output_tokens=out_tok,
            total_tokens=total_tok,
            cost_usd=cost_usd,
            status="success",
            input_preview=input_preview,
            output_preview=output_preview,
        )
        self.steps.append(step)

        if self.log_to_console:
            logger.info(json.dumps(step.to_log_dict()))

    def on_llm_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when LLM execution raises an exception."""
        run_key = str(run_id)
        active = self._active_runs.pop(run_key, None)
        end_perf = time.perf_counter()
        end_iso = datetime.now(timezone.utc).isoformat()

        start_perf = active["start_perf"] if active else end_perf
        start_iso = active["start_iso"] if active else end_iso
        latency_ms = round((end_perf - start_perf) * 1000.0, 2)

        self._step_counter += 1
        step = StepTelemetry(
            step_number=self._step_counter,
            step_type="llm_call",
            node_or_tool=active.get("name", "call_model") if active else "call_model",
            start_time=start_iso,
            end_time=end_iso,
            latency_ms=latency_ms,
            status="error",
            input_preview=active.get("preview", "") if active else "",
            output_preview="",
            error_message=str(error),
        )
        self.steps.append(step)

        if self.log_to_console:
            logger.error(json.dumps(step.to_log_dict()))

    # --- Tool Execution Events ---

    def on_tool_start(
        self,
        serialized: dict[str, Any] | None,
        input_str: str,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        inputs: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when a tool begins execution."""
        run_key = str(run_id)
        tool_name = (serialized or {}).get("name") or "unknown_tool"
        start_perf = time.perf_counter()
        start_iso = datetime.now(timezone.utc).isoformat()

        raw_in = inputs or input_str
        in_preview = str(raw_in)[:120].replace("\n", " ")

        self._active_runs[run_key] = {
            "type": "tool_execution",
            "name": tool_name,
            "start_perf": start_perf,
            "start_iso": start_iso,
            "preview": in_preview,
        }

    def on_tool_end(
        self,
        output: Any,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when a tool successfully concludes."""
        run_key = str(run_id)
        active = self._active_runs.pop(run_key, None)
        end_perf = time.perf_counter()
        end_iso = datetime.now(timezone.utc).isoformat()

        start_perf = active["start_perf"] if active else end_perf
        start_iso = active["start_iso"] if active else end_iso
        latency_ms = round((end_perf - start_perf) * 1000.0, 2)
        tool_name = active.get("name", "unknown_tool") if active else "unknown_tool"
        in_preview = active.get("preview", "") if active else ""
        out_preview = str(output)[:120].replace("\n", " ")

        self._step_counter += 1
        step = StepTelemetry(
            step_number=self._step_counter,
            step_type="tool_execution",
            node_or_tool=tool_name,
            start_time=start_iso,
            end_time=end_iso,
            latency_ms=latency_ms,
            input_tokens=0,
            output_tokens=0,
            total_tokens=0,
            cost_usd=0.0,
            status="success",
            input_preview=in_preview,
            output_preview=out_preview,
        )
        self.steps.append(step)

        if self.log_to_console:
            logger.info(json.dumps(step.to_log_dict()))

    def on_tool_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = None,
        **kwargs: Any,
    ) -> None:
        """Invoked when a tool encounters an error."""
        run_key = str(run_id)
        active = self._active_runs.pop(run_key, None)
        end_perf = time.perf_counter()
        end_iso = datetime.now(timezone.utc).isoformat()

        start_perf = active["start_perf"] if active else end_perf
        start_iso = active["start_iso"] if active else end_iso
        latency_ms = round((end_perf - start_perf) * 1000.0, 2)
        tool_name = active.get("name", "unknown_tool") if active else "unknown_tool"

        self._step_counter += 1
        step = StepTelemetry(
            step_number=self._step_counter,
            step_type="tool_execution",
            node_or_tool=tool_name,
            start_time=start_iso,
            end_time=end_iso,
            latency_ms=latency_ms,
            input_tokens=0,
            output_tokens=0,
            total_tokens=0,
            cost_usd=0.0,
            status="error",
            input_preview=active.get("preview", "") if active else "",
            output_preview="",
            error_message=str(error),
        )
        self.steps.append(step)

        if self.log_to_console:
            logger.error(json.dumps(step.to_log_dict()))

    # --- Summary Metrics ---

    def get_total_latency_ms(self) -> float:
        """Compute cumulative latency in milliseconds across all recorded steps."""
        return round(sum(s.latency_ms for s in self.steps), 2)

    def get_total_tokens(self) -> int:
        """Compute total token usage across all steps."""
        return sum(s.total_tokens for s in self.steps)

    def get_total_cost_usd(self) -> float:
        """Compute total estimated USD cost across all steps."""
        return round(sum(s.cost_usd for s in self.steps), 8)

    def format_summary_table(self) -> str:
        """Generate a formatted ASCII table report of per-step telemetry."""
        if not self.steps:
            return "No telemetry steps recorded."

        lines = [
            "=" * 88,
            " 📊 PRODUCTION STEP TELEMETRY REPORT (TASK 5.1)",
            "=" * 88,
            f"{'Step':<5} {'Type':<16} {'Node/Tool':<22} {'Latency':<12} "
            f"{'In Tok':<8} {'Out Tok':<8} {'Cost ($)':<12}",
            "-" * 88,
        ]

        for s in self.steps:
            lat_str = f"{s.latency_ms:.1f} ms"
            cost_str = f"${s.cost_usd:.6f}"
            lines.append(
                f"{s.step_number:<5} {s.step_type:<16} {s.node_or_tool[:20]:<22} "
                f"{lat_str:<12} {s.input_tokens:<8} {s.output_tokens:<8} {cost_str:<12}"
            )

        total_lat = self.get_total_latency_ms()
        lines.extend(
            [
                "-" * 88,
                (
                    f"TOTAL STEPS: {len(self.steps)} | DURATION: {total_lat:.2f} ms | "
                    f"TOKENS: {self.get_total_tokens()} | "
                    f"TOTAL COST: ${self.get_total_cost_usd():.6f}"
                ),
                "=" * 88,
            ]
        )
        return "\n".join(lines)


# -----------------------------------------------------------------------------
# 4. LangSmith Configuration Helper
# -----------------------------------------------------------------------------


def configure_langsmith_tracing(
    project_name: str | None = None,
    api_key: str | None = None,
    endpoint: str | None = None,
) -> bool:
    """Configure environment variables for native LangSmith cloud tracing.

    Args:
        project_name: LangSmith project name (defaults to 'phase-5-production').
        api_key: Optional LangSmith API key override.
        endpoint: Optional LangSmith endpoint override.

    Returns:
        True if LangSmith credentials are present and tracing is activated.
    """
    key = (
        api_key
        or os.environ.get("LANGSMITH_API_KEY")
        or os.environ.get("LANGCHAIN_API_KEY")
    )
    if not key:
        logger.info(
            "LangSmith API key not detected in environment. "
            "Using local StepTelemetryTracer for offline per-step metrics."
        )
        return False

    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    os.environ["LANGSMITH_TRACING"] = "true"
    os.environ["LANGCHAIN_API_KEY"] = key
    os.environ["LANGCHAIN_PROJECT"] = project_name or os.environ.get(
        "LANGCHAIN_PROJECT", "phase-5-production"
    )

    if endpoint:
        os.environ["LANGCHAIN_ENDPOINT"] = endpoint

    proj = os.environ["LANGCHAIN_PROJECT"]
    logger.info(f"LangSmith cloud tracing enabled for project '{proj}'.")
    return True
