"""Tests for Task 5.8: Reliability (Provider Fallback & Graceful Degradation)."""

from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock

import pytest
from langchain_core.messages import AIMessage
from phase_4_agents.rag_tools import db_query

from phase_5_production.reliability import (
    GracefulDegradationHandler,
    ProviderFailoverEvent,
    ReliableAgent,
    ReliableFallbackModel,
)


def make_mock_llm(
    return_value: Any = None,
    side_effect: Any = None,
) -> MagicMock:
    """Helper to construct MagicMock working for both direct call and .invoke()."""
    mock = MagicMock()
    if side_effect is not None:
        mock.side_effect = side_effect
        mock.invoke.side_effect = side_effect
    if return_value is not None:
        mock.return_value = return_value
        mock.invoke.return_value = return_value
    return mock


# =====================================================================
# PART 1: Provider Fallback on 429 Rate Limit & 503 Outages
# =====================================================================


def test_fallback_triggers_on_429_rate_limit() -> None:
    """Primary model throwing 429 must trigger automatic secondary failover."""
    primary_mock = make_mock_llm(
        side_effect=Exception("429 Too Many Requests: ResourceExhausted quota exceeded")
    )
    fallback_mock = make_mock_llm(
        return_value=AIMessage(content="Response generated by secondary provider.")
    )

    captured_events: list[ProviderFailoverEvent] = []
    model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
        primary_name="gemini-1.5-flash",
        fallback_name="gpt-4o-mini",
        failover_callback=captured_events.append,
    )

    result = model.invoke([AIMessage(content="Hello")])

    assert result.content == "Response generated by secondary provider."
    assert model.failover_count == 1
    assert model.primary_successes == 0
    assert model.fallback_successes == 1
    assert len(captured_events) == 1
    assert captured_events[0].reason == "rate_limit"
    assert captured_events[0].primary_provider == "gemini-1.5-flash"
    assert captured_events[0].fallback_provider == "gpt-4o-mini"


def test_fallback_triggers_on_503_service_outage() -> None:
    """Primary model throwing 503 Service Unavailable must trigger failover."""
    primary_mock = make_mock_llm(
        side_effect=Exception("503 Service Unavailable: High server load / outage")
    )
    fallback_mock = make_mock_llm(
        return_value=AIMessage(content="Fallback response during outage.")
    )

    captured_events: list[ProviderFailoverEvent] = []
    model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
        primary_name="gemini-primary",
        fallback_name="backup-provider",
        failover_callback=captured_events.append,
    )

    result = model.invoke([AIMessage(content="Status report")])

    assert result.content == "Fallback response during outage."
    assert model.failover_count == 1
    assert captured_events[0].reason == "outage"


def test_fallback_triggers_on_connection_timeout() -> None:
    """Connection timeouts to primary must failover gracefully."""
    primary_mock = make_mock_llm(
        side_effect=TimeoutError("Connection timed out to primary API gateway")
    )
    fallback_mock = make_mock_llm(
        return_value=AIMessage(content="Response served by backup provider.")
    )

    model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
    )

    result = model.invoke([AIMessage(content="Ping")])
    assert result.content == "Response served by backup provider."
    assert model.failover_count == 1


def test_non_transient_error_is_not_swallowed() -> None:
    """Non-transient programming errors (e.g. ValueError) must not trigger failover."""
    primary_mock = make_mock_llm(side_effect=ValueError("Invalid argument value"))
    fallback_mock = make_mock_llm()

    model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
    )

    with pytest.raises(ValueError, match="Invalid argument value"):
        model.invoke([AIMessage(content="Bad call")])

    assert fallback_mock.call_count == 0
    assert model.failover_count == 0


def test_both_providers_failing_raises_exception() -> None:
    """When both primary and secondary fail, the exception is propagated cleanly."""
    primary_mock = make_mock_llm(side_effect=Exception("500 Internal Server Error"))
    fallback_mock = make_mock_llm(side_effect=Exception("503 Backup unavailable"))

    model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
    )

    with pytest.raises(Exception, match="503 Backup unavailable"):
        model.invoke([AIMessage(content="Query")])


# =====================================================================
# PART 2: Graceful Degradation on Empty Retrieval
# =====================================================================


def test_degradation_handler_detects_empty_outputs() -> None:
    """Handler correctly identifies zero-record database and empty document outputs."""
    empty_db = (
        "Database Query Results:\n"
        "• Executed SQL: `SELECT ...`\n"
        "• Rows Returned: 0\n"
        "• No matching records found."
    )
    empty_pdf = "No relevant chunks found matching 'nonexistent-topic'."
    non_empty = "Database Query Results:\n• Rows Returned: 1\n• Records: {'id': 1}"

    assert GracefulDegradationHandler.is_empty_retrieval(empty_db) is True
    assert GracefulDegradationHandler.is_empty_retrieval(empty_pdf) is True
    assert GracefulDegradationHandler.is_empty_retrieval("") is True
    assert GracefulDegradationHandler.is_empty_retrieval(non_empty) is False


def test_degradation_handler_formats_grounded_answer() -> None:
    """Degradation notice provides truthful notice without hallucinating."""
    notice = GracefulDegradationHandler.create_degradation_response(
        query="find customers in Atlantis",
        tool_name="db_query",
        tool_output="• Rows Returned: 0\n• No matching records found.",
    )

    assert notice.searched_entity_or_topic == "find customers in Atlantis"
    assert "0 results" in notice.message
    assert len(notice.suggested_alternatives) >= 2

    formatted = GracefulDegradationHandler.format_grounded_answer(notice)
    assert "Notice: Information Not Found" in formatted
    assert "does not generate speculative or unverified answers" in formatted


# =====================================================================
# PART 3: End-to-End ReliableAgent Integration
# =====================================================================


def test_reliable_agent_failover_integration() -> None:
    """Agent seamlessly falls back to backup LLM and reports failover telemetry."""
    primary_mock = make_mock_llm(
        side_effect=Exception("429 Too Many Requests: Quota exceeded")
    )
    fallback_mock = make_mock_llm(
        return_value=AIMessage(content="Answer produced by fallback provider.")
    )

    fallback_model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
        primary_name="gemini-primary",
        fallback_name="openai-backup",
    )

    agent = ReliableAgent(fallback_model=fallback_model)
    res = agent.run_query("Explain planetary orbits.")

    assert res.response == "Answer produced by fallback provider."
    assert res.failover_occurred is True
    assert res.active_provider == "openai-backup"
    assert res.failover_reason == "rate_limit"
    assert res.is_degraded is False


def test_reliable_agent_empty_retrieval_degradation() -> None:
    """Agent gracefully degrades when tool finds no records without calling LLM."""
    primary_mock = make_mock_llm()
    fallback_mock = make_mock_llm()

    fallback_model = ReliableFallbackModel(
        primary_model=primary_mock,
        fallback_model=fallback_mock,
    )

    # Wire real db_query tool
    agent = ReliableAgent(
        fallback_model=fallback_model,
        tools_map={"db_query": lambda q: db_query.invoke({"query": q})},
    )

    # Query for city that does not exist in db
    res = agent.run_query(
        query="find customers in Atlantis",
        tool_name="db_query",
    )

    assert res.is_degraded is True
    assert "Notice: Information Not Found" in res.response
    assert "Atlantis" in res.response
    # Primary LLM was spared from hallucinating or generating fake customers
    assert primary_mock.call_count == 0
    assert fallback_mock.call_count == 0
